# Base off of the development image
FROM ner:latest
LABEL maintainer "Paul Annetts <paul.annetts@hutoma.com>"

USER root
WORKDIR /src
RUN pipenv install --system --dev

# Copy AI test training data
COPY tests/ /src/tests/

USER appuser
WORKDIR /home/appuser

CMD [ "pytest", "--cov=hu_entity", "/src/", "--tb=native"]
